on:
  # Test on PRs for any branch
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - v016
jobs:
  lints:
    strategy:
      matrix:
        rust:
          - nightly
    name: rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    strategy:
      matrix:
        rust:
          - nightly
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      
      - name: Test release-mode, default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      
      - name: Test release-mode, no default features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-default-features --tests
      
      - name: Test release-mode, alloc feature
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-default-features --features alloc --tests
